/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simo.kafkaimp3;

import simo.kafkaimp3.KafkaProducerWrapper;
import simo.kafkaimp3.KafkaConsumerWrapper;


public class App {

    public static void main(String[] args) {
        KafkaProducerWrapper p = new KafkaProducerWrapper();
        p.send();
        KafkaConsumerWrapper c = new KafkaConsumerWrapper();
        c.subscribeAndPrint();
    }
}
